---
title: "README"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem Set 01

Baby's first Kaggle competition and GitHub pull request! Specifically the [Titanic: Machine Learning from Disaster](<https://www.kaggle.com/c/titanic>) competition.

* Assigned: Thu 9/7
* Due: Mon 9/11 9:00am
* Teams: Individual
* Deliverables: A *pull request* to the [PS01 repo](https://github.com/2017-09-Amherst-STAT495/PS01) *at exactly* Mon 9/11 9:00am with
    + Title: Your name
    + The following files should be modified/added:
        1. `PS01.Rmd`: This should be well-commented and **completely reproducible**. In other words, if someone else takes this repo, they should be able to *reproduce* your work with one click of the mouse. This necessitates taking an empathetic view of other users.
        1. `PS01.html`: The output of `PS01.Rmd`
        1. `submission.csv`: Your predictions. Current set to match `gender_submissions.csv` on Kaggle.
        1. `screen_shot.png`: A screenshot of your Kaggle ranking. Be sure to "clean" your browsers.
        1. Any other necessary files.
